a = ['Apple', 'Guava', 'Mango', 'Banana', 'Kiwi']
print("Length of list:", len(a))
print("First Element:", a[0])
print("Last Element:", a[-1])
a.append('Papya')
print("Updated List :", a)
a.remove('Guava')
print("Updated List :", a)
a.sort()
print("Updated List :", a)
a.pop(1)
print("Updated List :", a)
a.reverse()
print("Reversed List :", a)
print("Multiplication List :", a*2)
a = a[:4]
print("Sliced List :", a)
a.clear()
print("Updated List :", a)